binary_sensor:

  - id: zone12
    name: Zone 12
    pin:
      pcf8574: inputs_9_16
      number: $zone12
      mode: INPUT
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      - script.execute: evaluate_alarm