binary_sensor:

  - id: zone13
    name: Zone 13
    pin:
      pcf8574: inputs_9_16
      number: $zone13
      mode: INPUT
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      - script.execute: evaluate_alarm