binary_sensor:

  - id: zone9
    name: Zone 9
    pin:
      pcf8574: inputs_9_16
      number: $zone9
      mode: INPUT
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      - script.execute: evaluate_alarm