binary_sensor:

  - id: zone15
    name: Zone 15
    pin:
      pcf8574: inputs_9_16
      number: $zone15
      mode: INPUT
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      - script.execute: evaluate_alarm